language: php
php:
  - 7.2
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
env:
  global:
    - SIMPLETEST_DB=sqlite://localhost/sites/default/files/.ht.sqlite
before_install:
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require "hirak/prestissimo:^0.3"
  - npm i -g npm bower
install:
  - composer create-project roundearth/drupal-civicrm-project:8.x-dev $TRAVIS_BUILD_DIR/../drupal --no-interaction
  - cd $TRAVIS_BUILD_DIR/../drupal
  - composer config repositories.drupal --unset
  - composer config repositories.0 '{"type": "path", "url": "'$TRAVIS_BUILD_DIR'"}'
  - composer config repositories.1 composer "https://packages.drupal.org/8
  - cat composer.json
  - composer require drupal/webform_civicrm *@dev

script:
  - cd $TRAVIS_BUILD_DIR/../drupal/web
  - ../vendor/bin/phpunit -c core modules/contrib/webform_civicrm
notifications:
  email: false
